### PR TITLE
Sound improvements for issue #20

### LINKED ISSUE #20: Additional event options for sound: answerOption on multi and last question
Two additional event options will provide good soundscaping possibilities. As with current `soundSrc` triggered "on submit," these additional are scoped game-wide vs per question or `answerOption`. All three events can use different sound sources, including **none**. 

```
soundSrc
multiAnswerSoundSrc
finalQuestionSoundSrc
```

Related to 
#14 
#18 
### Sound Events
- For `multi` formats, on `answerOption` selection (`multiAnswerSoundSrc`)
- on submit of the last question for all types / just before `getResults()` (`finalQuestionSoundSrc`)

Listening for `answerOption` clicks for `multi` formats lets us provide audio feedback on selections here, e.g.

image
	
Handling submit for the last question distinctly from previous ones lets us provide audio cues that the player has completed this part of the GamePath. 

We're looking for the same state as this `else` and optionally triggering a different sound.

https://github.com/smcnally/office_quiz/blob/master/src/App.js#L133
```
    // if no more questions, show result
    if (this.state.questionId < quizQuestions.length) {
      setTimeout(() => this.setNextQuestion(), 300);
    } else {
      setTimeout(() => this.setResults(this.getResults()), 300);
    }
```

### PR DESCRIPTION
**Pull request by rogertheriault**
Resolves #20 
1. allow soundSrc per-question, with 0 as default
2. allow multiAnswerSoundSrc per question (0 as default)
3. allow soundSrc per answer when multi (overrides default)
4. creates a helpers.js for "non component" helper functions, moves playSound there.

### CODE REVIEW

**Comment by rogertheriault** [comment]
@smcnally This should take care of the SFX. The quizQuestions.js references some files on localhost:5000 that I was serving locally. You can find a bunch of sfx files in a zip at https://opengameart.org/content/100-plus-game-sound-effects-wavoggm4a

**Comment by rogertheriault** [comment]
I should note you can customize the final sound just by setting the soundSrc in the final question.

**Comment by smcnally** [comment]
Sweet. Testing now. Using updates to Mozilla stuff as examples for this. Ty.

**Comment by smcnally** [comment]
Additional sounds are WaD. Approving, merging, closing this PR. 

Will follow-up re constraints as I update this GP execution:
https://games.gamepath.io/2018/05/11/mozilla-your-personal-data-and-you/

**Pull request merged**
